### PR TITLE
Add membership url

### PR DESCRIPTION
**Pull request by mchv**
This is a experiment to see how we can drive one of our off-platform audience to become supporters.
Due to the distributed nature of podcasts we don't know really how big the audience is!

@JuliaBellis

### CODE REVIEW

**Comment by mchv** [comment]
I am going to test this on `PROD` now

**Comment by cb372** [comment]
👍

**Comment by mchv** [comment]
This is not working as I expect as links seems to not be clickable in podcast summary in both app and web. The `summary` field does not seem to be used for the episode contrary to what the documentation explained.

**Comment by mchv** [comment]
I am redeploying master to `PROD` and will try to find podcast that do links and snatch their magic.

**Pull request closed without merging**
