### PR TITLE
Lowering snyk high from 6 to 0 and overall vulns from 75 to 10.

### PR DESCRIPTION
**Pull request by Divs-B**
## What does this change?

This is lowering down High snyk vulnerabilities from 6 to 0.
And total vulnerabilities (high/medium/low) from 75 to 10.

Jsoup Library (one of direct dependency) also rectified to latest version and with relative changes in the code by @fredex42.

Before: 

image

After 1st iteration: 

image

After 2nd iteration:

image

regarding Jsoup library:

image

## How to test

By running at localhost as mentioned in Readme and trying to load any RSS feed.

(While doing this PR, each library change has been tested via `sbt test` and `sbt run` and fetching podcast RSS feed successfully.)

## How can we measure success?

Server should run fine with no library errors/exceptions on console.

## Have we considered potential risks?

Shouldn't be case as we are doing this to making it highly secure

### CODE REVIEW

**Comment by Divs-B** [comment]
PR now looks great, Thank you @fredex42  for sorting out. This helped in resolving for both concerns mentioned earlier (1) Whitelist function error when upgrade to highest stable version for Jsoup and (2) Failing testcase in FilteringSpec.scala. 

Now Snyk screen showing 0 high and total 10 vulnerabilities at the moment.
image

**Comment by Divs-B** [comment]
Tested by `sbt test`,  then running it locally and fetching RSS feed, Hence moving draft PR to PR-to-review and if all okay then will merge. Thank you.

**Review by rowannekabalan — APPROVED** [review]
Nice one 👍 Would you mind just updating the PR description to reflect the final changes (as right now if someone reads it without the comments they would think we're still missing some fixes). We aim to have the PR description as accurate as possible for future reference. Thanks!

**Comment by Divs-B** [comment]
Thanks @rowannekabalan for valid concern, I'v updated the description.

**Pull request merged**
