### PR TITLE
Roll-out acast to next group of podcasts

### PR DESCRIPTION
**Pull request by gidsg**
Adds new series' to the Acast proxy whitelist and refactors code.

CC @mchv @guardian/commercial-dev

### CODE REVIEW

**Comment by gidsg** [comment]
[complete acast roll-out](https://trello.com/c/7eC9iIBq/207-complete-acast-roll-out)

**Comment by mchv** [comment]
👍

**Comment by gidsg** [comment]
@mchv Do not merge yet, I am just waiting for OK from Acast.

**Comment by gidsg** [comment]
OK, @mchv we have 👍 from Acast side, so happy for you to merge this.

**Pull request merged**
